name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test and compile
      run: |
        for d in */ ; do
        cd "$d"
        make
        cd ..
        done
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: |
          ./lab7/MarriageAgency.cpp.gcov
          ./lab7/People.cpp.gcov
